Repository Theoyeah/Theoyeah-Engine, pull requests merged in 2022-06, with the labels that each got.

#165 Die revive option
  source/ClientPrefs.hx
  source/GameOverSubstate.hx
  source/Paths.hx
  source/options/GameplaySettingsSubState.hx
Labels: Needs someone to test, Ready for review

#153 More things and adding mkv videos
  Project.xml
  source/Paths.hx
  source/PlayState.hx
Labels: Finished, Ready for review

#145 Cheating allowed repaired
  source/FreeplayState.hx
  source/GameplayChangersSubstate.hx
  source/PlayState.hx
  source/StoryMenuState.hx
  source/options/GameplaySettingsSubState.hx
Labels: Finished, Ready for review

#205 Combo Sprite Support
  source/ClientPrefs.hx
  source/PlayState.hx
  source/editors/EditorPlayState.hx
  source/options/NoteOffsetState.hx
Labels: IMPORTANT, God, Finished
